# Generated by Django 4.2.27 on 2026-05-31 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsLeague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(default='', max_length=4)),
            ],
            options={
                'ordering': ['name', 'short_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name', 'short_name']},
        ),
        migrations.AddField(
            model_name='team',
            name='short_name',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='home.sportsleague')),
                ('loser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='losing_selections', to='home.team')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='home.player')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winning_selections', to='home.team')),
            ],
        ),
    ]
