# Generated by Django 4.2.27 on 2026-08-19 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_sportsleague_alter_team_options_team_short_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportsleague',
            name='bbc_name_slug',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sportsleague',
            name='last_updated',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='TeamStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='home.sportsleague')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='home.team')),
            ],
        ),
    ]
