# Generated by Django 4.2.27 on 2026-08-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_sportsleague_bbc_name_slug_sportsleague_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamstanding',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sportsleague',
            name='bbc_name_slug',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
