# Generated by Django 4.2.27 on 2026-08-22 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_teamstanding_rank_alter_sportsleague_bbc_name_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sportsleague',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='sportsleague',
            name='short_name',
        ),
    ]
