# Generated by Django 4.2.27 on 2026-08-22 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_sportsleague_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='team',
            name='short_name',
        ),
    ]
