# Generated by Django 4.2.27 on 2026-08-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_team_options_remove_team_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportsleague',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
