# Generated by Django 4.2.27 on 2026-09-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_selection_ff_league'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ffleague',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sportsleague',
            options={'ordering': ['order_idx']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={},
        ),
        migrations.AddField(
            model_name='sportsleague',
            name='order_idx',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ffleague',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='players', to='home.player'),
        ),
    ]
